global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gamba-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend1:8000
          - backend2:8000
          - backend3:8000
          - backend4:8000
          - backend5:8000